### ISSUE TITLE
Support custom request id

### ISSUE THREAD

**Issue by marcbachmann** [davidmarkclements/pino-http#3]
I'm already using a request id on req.id (gets set by external load balancer).
This module overwrites that one with an incrementing id, which results in duplicated request ids if I have multiple processes running.

```js
if (!req.id) {
  req.id = ++nextId
  nextId = ...
}
```
Do you think that is good enough?

**Comment by davidmarkclements** [comment]
agreed this is needed - will accept PR :) - currently on low bandwidth - out of curiosity what load balancer does this?

**Comment by marcbachmann** [comment]
I'll create a pr.

> out of curiosity what load balancer does this?

Heroku uses the http header `X-Request-ID`
https://devcenter.heroku.com/articles/http-request-id.

haproxy also supports a unique header
http://cbonte.github.io/haproxy-dconv/configuration-1.5.html#4-unique-id-header
